name: Workflows
on: [push]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - run: bundle exec rake rubocop
  specs:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: if [[ $(uname) == "Darwin" ]]; then brew install capstone; else sudo apt-get install libcapstone4; fi
    - run: bundle exec rake specs
  specs-no-dependencies:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.1']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - env:
        NO_DEPENDENCIES_INSTALLED: true
      run: bundle exec rake specs
